import json
from pydantic import ValidationError
from .data_model import BuildJSON
from pathlib import Path
from typing import Any
from .arguments import (
    get_arguments,
    get_functions_definition,
    get_functions_calling_tests,
)
from .mind_llm import LLMInterface
import time
import sys
from functools import wraps


def measure_time(function: Any) -> Any:
    """
    Measure and display the execution time of a function.

    This decorator records the start and end time of the wrapped
    function using ``time.perf_counter()`` and prints the total
    execution time in minutes.

    Args:
        function: Function to be wrapped.

    Returns:
        Callable: Wrapped function that prints its execution time
        before returning the original result.
    """
    @wraps(function)
    def envelope(*args: Any, **kwargs: Any) -> Any:
        start = time.perf_counter()

        result = function(*args, **kwargs)

        end = time.perf_counter()

        total_time = end - start
        time_in_minutes = total_time / 60
        print(
            f"\n[⏱️ Execution time of '{function.__name__}':"
            f"{time_in_minutes:.2f} minutes]"
        )

        return result
    return envelope


def cast_value(value: str, expected_type: str) -> Any:
    """
    Convert a string value into the expected Python type.

    The expected type is obtained from the function definition and is
    used to convert parameter values before storing the generated JSON.

    Supported conversions are:
        - number -> int or float
        - integer -> int
        - boolean -> bool
        - string -> str

    Args:
        value: Parameter value generated by the language model.
        expected_type: Expected parameter type defined in
            ``functions_definition.json``.

    Returns:
        Any: Converted value using the expected Python type.
    """
    if expected_type == "number":

        number = float(value)

        if number.is_integer():
            return int(number)

        return number

    if expected_type == "integer":
        return int(value)

    if expected_type == "boolean":
        return value.lower() == "true"

    return value


@measure_time
def main() -> None:
    try:
        args = get_arguments()
    except Exception as ex:
        print(f'Invalid arguments. Please use --help to get help.'
              f' ({ex})')
        sys.exit(1)

    try:
        functions_definition = get_functions_definition(args)

        prompts = get_functions_calling_tests(args)

        interface = LLMInterface("Qwen/Qwen3-0.6B", functions_definition)

        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        result_json = []

        for test in prompts:

            generated = interface.generate_json(test.prompt)
            json_text = '{"name":"' + generated
            data = json.loads(json_text)
            func = next(
                f for f in functions_definition
                if f.name == data["name"]
            )

            parameters = {}

            for key, value in data["parameters"].items():
                expected_type = func.parameters[key]["type"]
                parameters[key] = cast_value(value, expected_type)

            result = BuildJSON(
                prompt=test.prompt,
                name=data["name"],
                parameters=parameters
            )

            result_json.append(result)

        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(
                [r.model_dump() for r in result_json],
                f,
                indent=4,
                ensure_ascii=False,
            )

        print(f"\n[INFO] File saved successfully in: {output_path}")

    except ValidationError as e:
        print(f"Invalid: {e}")
    except json.JSONDecodeError:
        print("File invalid JSON")


if __name__ == "__main__":
    main()
